### ISSUE TITLE
Allow subfolders within the notes folder

### ISSUE THREAD

**Issue by RosieCampbell** [b3u/eleventy-garden#9]
I'd like to be able to organize my notes into folders e.g. 'Recipes', 'Evergreen notes' etc - currently this doesn't work.

I'm not sure if the folder hierarchy should be reflected in the URL (e.g. `/Recipes/Tomato-soup`) or if it should just resolve to the note name (e.g. `/Tomato-soup`). Maybe this could be configurable?

**Comment by b3u** [comment]
> ...currently this doesn't work

Can you elaborate on that? It worked for me when I added a page within a subfolder.

The only thing was that when I linked to it, I had to include the subfolder in the link, as in `[[ subfolder/note | note]]`. This is important, because the subfolder could have a note with the same name as a note in the main folder.

**Comment by RosieCampbell** [comment]
You're right! It works when I include the subfolder. Awesome!

**Comment by b3u** [comment]
This should probably be documented somewhere...

**Comment by b3u** [comment]
Documented in [wiki faq](https://github.com/b3u/eleventy-garden/wiki/FAQ)
